version: "3.7"
services:
  go:
    build: ./
    ports:
      - 80:80
    environment:
      API_PORT: 80
    volumes:
      - ./static:/static
  database:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "core"